version: "3.7"
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - hello-server

  hello-server:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
